[opener]
yacreader = [
  { run = '/Applications/YACReader.app/Contents/MacOS/YACReader %s', orphan = true, desc = "YACReader" },
]
preview = [
  { run = 'open -a "Preview" %s', orphan = true, desc = "Preview" },
]

[open]
prepend_rules = [
  { mime = "application/vnd.comicbook+zip", use = "yacreader" },
  { mime = "application/vnd.comicbook-rar", use = "yacreader" },
  { url = "*.cbz", use = "yacreader" },
  { url = "*.cbr", use = "yacreader" },
  { mime = "application/pdf", use = ["preview", "yacreader"] },
  { url = "*.pdf", use = ["preview", "yacreader"] },
]
